### ISSUE TITLE
About file listening

### ISSUE THREAD

**Issue by Globik** [kentor/node-hot-reloading-boilerplate#1]
A question is if chockidar is watching the .js files in the current directory or all over the OS computer?
And watcher.close() is a need if persistent options is false(memory leaks issue)?
In your boilerplate you require and rerequire one module 'build.js'. And what if will be one more modules?
Simpli by all event invalidate a module?

**Comment by kentor** [comment]
- current directory
- i'm not sure what the point of `persistent: false` is.
- if a module is updated then it will be invalidated. best way to see how this work is try yourself

the readme at https://github.com/kentor/invalidate-module has an example with multiple modules

**Comment by Globik** [comment]
Persistent is true by default. One need also add watcher.close() for the case of proccess.on'SIGINT' event.
